### ISSUE TITLE
Infinite Jumps

### ISSUE THREAD

**Issue by LiamDavisSAE** [HotdogsCC/Project-Orphia#13]
**Describe the bug**
Orphia can continue to jump infinitely.

1. Press space.
2. Press space again.
3. Press space again.
4. See error.

**Expected behaviour**
The player should only be able to jump 2 times.

![Screenshot (228)](https://github.com/HotdogsCC/Project-Orphia/assets/114543370/c5e4b97b-d06b-45d8-8fdd-a953481adc14)

**Comment by HotdogsCC** [comment]
![image](https://github.com/HotdogsCC/Project-Orphia/assets/87422910/dffd446b-65e2-413e-8045-05427d576faa)

The bug was caused by the ground detecting raycasting hitting anything, thus allowing the player to jump. The solution is to mark all jumpable platforms with the "jumpable" tag.
